### ISSUE TITLE
Having problems installing HFST and using emMorphPy on Windows

### ISSUE THREAD

**Issue by ivanalaterza** [dlt-rilmta/emmorphpy#1]
hfst installation for Windows doesn't work - I followed the instructions given here https://github.com/hfst/hfst - with no success. I can't use emmorphpy without hfst. anyone else having the same issue? Please advise how to resolve this. Thanks!

**Comment by dlazesz** [comment]
I'm sorry to disappoint you, but emMorphPy is not tested under Windows and only guaranteed to work under Linux. Even with proper installation of HFST it will not work, I have recently tested it and [fixed an encoding bug presents only on Windows](https://github.com/dlt-rilmta/emmorphpy/commit/8502963fd782d5e3aba903c871b30d97233ba69e).

[The class `EmMorphPy()` has a parameter `hfst_lookup`](https://github.com/dlt-rilmta/emmorphpy/blob/8502963fd782d5e3aba903c871b30d97233ba69e/emmorphpy/emmorphpy.py#L22) where you can set the location of `hfst-lookup` executable which has to be installed from http://apertium.projectjj.com/win32/release/hfst-latest.zip by putting the following files into a directory in path (or set the absolute path of the file hfst-lookup.exe as parameter) :

- hfst-lookup.exe
- icuuc65.dll
- libgcc_s_sjlj-1.dll
- libstdc++-6.dll
- icudt65.dll
- libdl.dll
- libhfst-53.dll
- libwinpthread-1.dll

When `hfst-lookup` can be accessed, the initialization of the class will be blocked by [`readline()`](https://github.com/dlt-rilmta/emmorphpy/blob/8502963fd782d5e3aba903c871b30d97233ba69e/emmorphpy/emmorphpy.py#L597) as `readline()` blocks on Windows and returns empty string on Linux.

To make it work in a platform independent way, the [whole IO handling have to be rewritten](https://stackoverflow.com/questions/375427/a-non-blocking-read-on-a-subprocess-pipe-in-python/4896288#4896288). Which will obviously not going to happen as [Quntoken](https://github.com/dlt-rilmta/quntoken) also does not support Windows.

I recommend using

- Ubuntu
- [emtsv Docker](https://github.com/dlt-rilmta/emtsv#docker-image) on [Docker Desktop for Windows](https://hub.docker.com/editions/community/docker-ce-desktop-windows)
- [WSL](https://docs.microsoft.com/en-us/windows/wsl/install-win10) preferably [WSL2](https://www.omgubuntu.co.uk/how-to-install-wsl2-on-windows-10)
- Free [REST API](https://github.com/dlt-rilmta/emmorphpy#usage) service (which has its own limitations, but you can setup your own version following [the guide](https://github.com/dlt-rilmta/emmorphpy#install-to-heroku)): https://emmorph.herokuapp.com/
